name: project deployment
on:
  push:
    branches: [master]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: run ssh
        uses: appleboy/ssh-action@v1
        with:
          host: 183.101.189.204
          username: test
          password: qwer1234
          port: 122
          script: |
            rm -rf ./docker_pr
            git clone https://github.com/flionme/docker_pr.git
            cd ./docker_pr
            chmod +x ./gradlew
            ./gradlew bootJar
            ls build/libs  # JAR 생성 확인
            docker rm -f back || true
            docker image prune -f
            docker build --tag itjusttest/back:latest .
            docker run -d --name back -p 8080:8080 itjusttest/back:latest
